spring.application.name=email-analyzer


#BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/email_analyzer
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA    
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#AWS
aws.region=us-east-1
aws.bedrock.model-id=amazon.nova-lite-v1:0


